export const _lang = {
  'BG': {
    'LOGIN': {
      'PIN_ACCESS': 'ПИН достъп',
      'WRONG_PIN': 'Грешен ПИН!',
      'LOGIN': 'Вход',
      'PASSPHRASE_ACCESS': 'Достъп с фраза',
      'ENTER_PASSPHRASE': 'Въведете фраза',
      'OVERRIDE_PIN': 'Създаване / Промяна ПИН',
      'ENTER_6_DIGIT_PIN': 'Въведете ПИН (мин. 6 цифри)',
      'PIN_TOO_SHORT': 'Кратък ПИН!',
      'I_CONFIRM_I_SAVED_SEED': 'Потвърждавам, че съм записал фразата',
      'PLEASE_MAKE_SURE_TO': 'Убедете се, че сте я записали и я съхранявайте на сигурно място!',
      'THIS_IS_YOUR_NEW_SEED': 'Това е новата Ви фраза',
      'CONFIRMATION_REQUIRED': 'Потвърдете',
    },
    'SEND': {
      'SEND': 'Изпрати',
      'BACK': 'Назад',
      'SEND_FROM': 'Изпрати от',
      'SEND_TO': 'Изпрати до',
      'ENTER_AN_ADDRESS': 'Въведете адрес',
      'AMOUNT': 'Сума',
      'FILL_IN_DETAILS': 'Попълнете детайлите',
      'CONFIRM': 'Потвърждение',
      'TO': 'До',
      'FROM': 'От',
      'WARNING': 'Внимание',
      'WARNING_SPV_P1': 'данните за портфейла Ви са потвърдени само от един сървър!',
      'WARNING_SPV_P2': 'Ако искате да продължите, натиснете "Потвърждение".',
      'SPV_VERIFYING': 'Проверка на транзакцията',
      'TX_RESULT': 'Резултат от транзакцията',
      'KEY': 'Ключ',
      'INFO': 'Информация',
      'RESULT': 'Резултат',
      'SUCCESS': 'успех',
      'PROCESSING_SM': 'обработва се...',
      'PROCESSING_TX': 'Транзакцията се обработва...',
      'ERROR': 'Грешка',
      'MAKE_ANOTHER_TX': 'Нова транзакция',
      'NAN': 'Не е число',
      'TOO_MUCH': 'Сумата е много голяма. Макс. налична сума е @template@',
      'ADDRESS_IS_INCORECT': 'Адресът е неправилен',
      'QR_SCAN_ERR': 'Неуспешно декодиране на QR код. Моля, опитайте отново.',
      'SCAN_QR': 'Сканиране QR код',
    },
    'ADD_COIN': {
      'ADD_ALL_COINS': 'Добави всички валути',
      'SHORTCUTS': 'Бързи връзки',
      'MULTI_SELECT': 'Избор на няколко',
      'ADD_SELECTED_COINS': 'Добави избраните валути',
    },
    'BALANCE': {
      'BALANCE': 'Баланс',
      'INTEREST': 'Лихва',
    },
    'DASHBOARD': {
      'MY': 'Моят',
      'ADDRESS': 'адрес',
      'TRANSACTIONS': 'Транзакции',
      'BACK': 'Назад',
      'LOGOUT': 'Изход',
      'LOGIN': 'Вход',
      'LOCK': 'Заключи',
      'DASHBOARD': 'Табло',
      'SEND': 'Изпращане',
      'RECEIVE': 'Получаване',
      'ADD_COIN': 'Добави валута',
      'CREATE_SEED': 'Създай фраза',
      'CON_ERROR': 'Грешка при връзка. Моля, опитайте друг @template@ сървър.',
      'SWITCH_SERVER': 'Смяна на сървър',
      'ERROR_TESTING_SERVER': 'Грешка: сървър @template@ не е достъпен!',
      'CONNECTING_TO_NEW_SERVER': 'Свързване към нов сървър...',
      'PROXY_ERROR': 'Прокси услугата е недостъпна!',
      'CLAIM': 'Усвои',
    },
    'TRANSACTIONS': {
      'OUT': 'изх.',
      'IN': 'вх.',
      'MINE': 'потв.',
      'IMMATURE': 'скорошни',
      'UKNOWN': 'неизв.',
      'NO_HISTORY': 'Няма история',
      'DIRECTION': 'Позока',
      'CONFIRMATIONS': 'Потвърждения',
      'INTEREST': 'Лихва',
      'TX_HASH': 'Тр. хеш',
      'AMOUNT': 'Сума',
      'TIME': 'Време',
    },
    'CLAIM': {
      'WARNING': 'Внимание',
      'WARNING_SPV_P1': 'данните за портфейла Ви са потвърдени само от един сървър!',
      'WARNING_SPV_P2': 'Ако искате да продължите, натиснете "Потвърждение".',
      'SPV_VERIFYING': 'Проверка на транзакцията',
      'CONFIRM': 'Потвърждение',
      'CANCEL': 'Отказ',
      'FAILED_TO_CLAIM_INTEREST': 'Грешка при усвояване на лихвата! Моля, опитайте отново.',
      'YOU_SUCCESFULLY_CLAIMED': 'Успешно усвояване',
      'AMOUNT': 'Сума',
      'INTEREST': 'Лихва',
      'INTEREST_SM': 'лихва',
      'LIST_SM': 'списък',
      'REQ_TO_CLAIM_P1': 'Изисквания за получаване на лихва',
      'REQ_TO_CLAIM_P2': 'транзакцията да е направена преди повече от час, времето на заключване да е зададено и сумата да е повече от 10 KMD',
      'CLAIM': 'Усвои',
    },
  },
};