export const _lang = {
  'EN': {
    'LOGIN': {
      'PIN_ACCESS': 'PIN access',
      'WRONG_PIN': 'Wrong PIN!',
      'LOGIN': 'Login',
      'PASSPHRASE_ACCESS': 'Passphrase access',
      'ENTER_PASSPHRASE': 'Enter a passphrase',
      'OVERRIDE_PIN': 'Create / Override PIN',
      'ENTER_6_DIGIT_PIN': 'Enter a PIN (min. 6 digits)',
      'PIN_TOO_SHORT': 'PIN is too short!',
      'I_CONFIRM_I_SAVED_SEED': 'I confirm that I saved the seed',
      'PLEASE_MAKE_SURE_TO': 'Please make sure to write it down and store in a safe place!',
      'THIS_IS_YOUR_NEW_SEED': 'This is your new seed',
      'CONFIRMATION_REQUIRED': 'Confirmation is required',
    },
    'SEND': {
      'SEND': 'Send',
      'BACK': 'Back',
      'SEND_FROM': 'Send from',
      'SEND_TO': 'Send to',
      'ENTER_AN_ADDRESS': 'Enter an address',
      'AMOUNT': 'Amount',
      'FILL_IN_DETAILS': 'Fill in details',
      'CONFIRM': 'Confirm',
      'TO': 'To',
      'WARNING': 'Warning',
      'WARNING_SPV_P1': 'your wallet data is verified only by a single server!',
      'WARNING_SPV_P2': 'If you still want to continue press "Confirm".',
      'SPV_VERIFYING': 'Verifying transaction data',
      'TX_RESULT': 'Transaction result',
      'KEY': 'Key',
      'INFO': 'Info',
      'RESULT': 'Result',
      'SUCCESS': 'success',
      'PROCESSING_SM': 'processing...',
      'PROCESSING_TX': 'Processing transaction...',
      'ERROR': 'Error',
      'MAKE_ANOTHER_TX': 'Make another tx',
      'NAN': 'Not a number',
      'TOO_MUCH': 'Number is too big. Max. available amount is @template@',
      'ADDRESS_IS_INCORECT': 'Address is incorrect',
    },
    'ADD_COIN': {
      'ADD_ALL_COINS': 'Add all coins',
      'SHORTCUTS': 'Shortcuts',
      'MULTI_SELECT': 'Multi-select',
      'ADD_SELECTED_COINS': 'Add selected coins',
    },
    'BALANCE': {
      'BALANCE': 'Balance',
      'INTEREST': 'Interest',
    },
    'DASHBOARD': {
      'MY': 'My',
      'ADDRESS': 'address',
      'LOGOUT': 'Logout',
      'LOGIN': 'Login',
      'LOCK': 'Lock',
      'DASHBOARD': 'Dashboard',
      'SEND': 'Send',
      'ADD_COIN': 'Add coin',
      'CREATE_SEED': 'Create seed',
      'CON_ERROR': 'Connection error. Please try another @template@ server.',
      'SWITCH_SERVER': 'Switch server',
      'ERROR_TESTING_SERVER': 'Error: server @template@ is unreachable!',
      'CONNECTING_TO_NEW_SERVER': 'Connecting to a new server...',
      'PROXY_ERROR': 'Proxy service is unreachable!',
    },
    'TRANSACTIONS': {
      'OUT': 'out',
      'IN': 'in',
      'MINE': 'mine',
      'IMMATURE': 'immature',
      'UKNOWN': 'uknown',
      'NO_HISTORY': 'No history',
    },
  },
};