export const _lang = {
  'EN': {
    'LOGIN': {
      'PIN_ACCESS': 'PIN access',
      'WRONG_PIN': 'Wrong PIN!',
      'LOGIN': 'Login',
      'PASSPHRASE_ACCESS': 'Passphrase access',
      'ENTER_PASSPHRASE': 'Enter a passphrase',
      'OVERRIDE_PIN': 'Create / Override PIN',
      'ENTER_6_DIGIT_PIN': 'Enter a PIN (min. 6 digits)',
      'PIN_TOO_SHORT': 'PIN is too short!',
      'I_CONFIRM_I_SAVED_SEED': 'I confirm that I saved the seed',
      'PLEASE_MAKE_SURE_TO': 'Please make sure to write it down and store in a safe place!',
      'THIS_IS_YOUR_NEW_SEED': 'This is your new seed',
      'CONFIRMATION_REQUIRED': 'Confirmation is required',
    },
    'SEND': {
      'SEND': 'Send',
      'BACK': 'Back',
      'SEND_FROM': 'Send from',
      'SEND_TO': 'Send to',
      'ENTER_AN_ADDRESS': 'Enter an address',
      'AMOUNT': 'Amount',
      'FILL_IN_DETAILS': 'Fill in details',
      'CONFIRM': 'Confirm',
      'TO': 'To',
      'FROM': 'From',
      'WARNING': 'Warning',
      'WARNING_SPV_P1': 'your wallet data is verified only by a single server!',
      'WARNING_SPV_P2': 'If you still want to continue press "Confirm".',
      'SPV_VERIFYING': 'Verifying transaction data',
      'TX_RESULT': 'Transaction result',
      'KEY': 'Key',
      'INFO': 'Info',
      'RESULT': 'Result',
      'SUCCESS': 'success',
      'PROCESSING_SM': 'processing...',
      'PROCESSING_TX': 'Processing transaction...',
      'ERROR': 'Error',
      'MAKE_ANOTHER_TX': 'Send another',
      'NAN': 'Not a number',
      'TOO_MUCH': 'Number is too big. Max. available amount is @template@',
      'ADDRESS_IS_INCORECT': 'Address is incorrect',
      'QR_SCAN_ERR': 'Unable to decode QR image. Please retry.',
      'SCAN_QR': 'Scan QR code',
    },
    'ADD_COIN': {
      'ADD_ALL_COINS': 'Add all coins',
      'SHORTCUTS': 'Shortcuts',
      'MULTI_SELECT': 'Multi-select',
      'ADD_SELECTED_COINS': 'Add selected coins',
    },
    'BALANCE': {
      'BALANCE': 'Balance',
      'INTEREST': 'Interest',
    },
    'DASHBOARD': {
      'MY': 'My',
      'ADDRESS': 'address',
      'TRANSACTIONS': 'Transactions',
      'BACK': 'Back',
      'LOGOUT': 'Logout',
      'LOGIN': 'Login',
      'LOCK': 'Lock',
      'DASHBOARD': 'Dashboard',
      'SEND': 'Send',
      'RECEIVE': 'Receive',
      'ADD_COIN': 'Add coin',
      'CREATE_SEED': 'Create seed',
      'CON_ERROR': 'Connection error. Please try another @template@ server.',
      'SWITCH_SERVER': 'Switch server',
      'ERROR_TESTING_SERVER': 'Error: server @template@ is unreachable!',
      'CONNECTING_TO_NEW_SERVER': 'Connecting to a new server...',
      'PROXY_ERROR': 'Proxy service is unreachable!',
      'CLAIM': 'Claim',
    },
    'TRANSACTIONS': {
      'OUT': 'out',
      'IN': 'in',
      'MINE': 'mine',
      'IMMATURE': 'immature',
      'UNKNOWN': 'unknown',
      'NO_HISTORY': 'No history',
      'DIRECTION': 'Direction',
      'CONFIRMATIONS': 'Confirmations',
      'INTEREST': 'Interest',
      'TX_HASH': 'Tx hash',
      'AMOUNT': 'Amount',
      'TIME': 'Time',
    },
    'CLAIM': {
      'WARNING': 'Warning',
      'WARNING_SPV_P1': 'your wallet data is verified only by a single server!',
      'WARNING_SPV_P2': 'If you still want to continue press "Confirm".',
      'SPV_VERIFYING': 'Verifying transaction data',
      'CONFIRM': 'Confirm',
      'CANCEL': 'Cancel',
      'FAILED_TO_CLAIM_INTEREST': 'Failed to claim interest! Please retry.',
      'YOU_SUCCESFULLY_CLAIMED': 'You succesfully claimed',
      'AMOUNT': 'Amount',
      'INTEREST': 'Interest',
      'INTEREST_SM': 'interest',
      'LIST_SM': 'list',
      'REQ_TO_CLAIM_P1': 'Requirements to accrue interest',
      'REQ_TO_CLAIM_P2': 'spend transaction was made at least 1 hour ago, locktime field is set and amount is greater than 10 KMD',
      'CLAIM': 'Claim',
    },
    'APP_TITLE': {
      'PIN': 'Override PIN',
      'LOGIN': 'Sign in',
      'DASHBOARD': 'Dashboard',
      'OVERVIEW': 'Overview',
      'SETTINGS': 'Settings',
      'RECOVERY': 'Recovery',
      'SEND': 'Send',
      'OFFLINESIG': 'Offline signing',
      'ADDCOIN': 'Add coin',
      'CREATE-SEED': 'Create seed',
      '': '',
    },
    'COINS': {
      // asset chains
      'BET': 'BET',
      'BOTS': 'BOTS',
      'CEAL': 'CEAL NET',
      'COQUI': 'COQUI',
      'CHAIN': 'Chainmakers',
      'GLXT': 'GLXToken',
      'EQL': 'Equaliser',
      'CRYPTO': 'CRYPTO',
      'HODL': 'HODL',
      'DEX': 'DEX',
      'JUMBLR': 'JUMBLR',
      'KV': 'KV',
      'MGW': 'MultiGateway',
      'MVP': 'MVP Lineup',
      'MNZ': 'Monaize',
      'PANGEA': 'PANGEA',
      'REVS': 'REVS',
      'MSHARK': 'MSHARK',
      'SHARK': 'SHARK',
      'MESH': 'SpaceMesh',
      'SUPERNET': 'SUPERNET',
      'WLC': 'WIRELESS',
      'AXO': 'AXO',
      'ETOMIC': 'ETOMIC',
      'BTCH': 'BTCH',
      'BEER': 'BEER (Test coin)',
      'PIZZA': 'PIZZA (Test coin)',
      'VOTE2018': 'VOTE2018 (Notary Elections)',
      'NINJA': 'NINJA',
      'GLXT': 'GLXToken',
      'BNTN': 'Blocnation',
      'PRLPAY': 'Pearl Pay',
      'OOT': 'Utrum',
      // crypto
      'CRW': 'Crown',
      'STRAT': 'Stratis',
      'TOA': 'TOA',
      'USC': 'UltimateSecureCash',
      'VPN': 'VpnCoin',
      'WC': 'WinCoin',
      'NRG': 'Energi',
      'ABY': 'ArtByte',
      'VOT': 'VoteCoin',
      'BDL': 'Bitdeal',
      'BTCP': 'BitcoinPrivate',
      'MAC': 'Machinecoin',
      'XWC': 'Whitecoin',
      'XVC': 'Vcash',
      'SMART': 'Smartcash',
      'CRAVE': 'Crave',
      'ACC': 'AdCoin',
      'AC': 'AsiaCoin',
      'AUR': 'Auroracoin',
      'BCA': 'Bitcoin Atom',
      'CLAM': 'Clams',
      'CLUB': 'ClubCoin',
      'DMD': 'Diamond',
      'EXCL': 'ExclusiveCoin',
      'FTC': 'FeatherCoin',
      'FLASH': 'Flash',
      'NLG': 'Gulden',
      'LCC': 'Litecoin Cash',
      'MNX': 'MinexCoin',
      'NAV': 'NavCoin',
      'NEOS': 'NeosCoin',
      'OK': 'OKCash',
      'OMNI': 'OmniLayer',
      'PIVX': 'Pivx',
      'RDD': 'Reddcoin',
      'UNO': 'Unobtanium',
      'XVG': 'Verge',
      'VIVO': 'VIVO',
      'EFL': 'E-Gulden',
      'GBX': 'GoByte',
      'BSD': 'Bitsend',
      'LBC': 'LBRY Credits',
      'ERC': 'Europecoin',
      'BATA': 'Bata',
      'EMC2': 'Einsteinium',
      'SYS': 'Syscoin',
      'IOP': 'Internet of People',
      'ZEN': 'Zencash',
      'XZC': 'Zcoin',
      'FJC': 'Fujicoin',
      'GAME': 'GameCredits',
      'BCBC': 'Bitcoin CBC',
      'BTG': 'BitcoinGold',
      'BCH': 'BitcoinCash',
      'BTC': 'Bitcoin',
      'DASH': 'Dash',
      'DNR': 'Denarius',
      'DGB': 'DigiByte',
      'FAIR': 'Faircoin',
      'ARG': 'Argentum',
      'LTC': 'Litecoin',
      'MONA': 'Monacoin',
      'NMC': 'Namecoin',
      'VTC': 'Vertcoin',
      'VIA': 'Viacoin',
      'SIB': 'Sibcoin',
      'BLK': 'Blackcoin',
      'DOGE': 'Dogecoin',
      'ZEC': 'Zcash',
      'HUSH': 'Hush',
      'SNG': 'SnowGem',
      'ZCL': 'Zclassic',
      'XMY': 'Myriad',
      'GRS': 'Groestlcoin',
      'HODLC': 'Hodl coin',
      'BTX': 'Bitcore',
      'QTUM': 'Qtum',
      'BTCZ': 'BitcoinZ',
      'KMD': 'Komodo',
      'CHIPS': 'Chips',
      'MZC': 'Mazacoin',
      'ZET': 'Zetacoin',
      'SLR': 'Solarcoin',
      'SMLY': 'Smileycoin',
      'RBY': 'Rubycoin',
      'VOX': 'RevolutionVR',
      'PUT': 'PutinCoin',
      'POT': 'Potcoin',
      'POSW': 'Poswcoin',
      'PINK': 'Pinkcoin',
      'PSB': 'Pesobit',
      'NSR': 'NuShares',
      'NVC': 'Novacoin',
      'NYC': 'NewYorkCoin',
      'NRO': 'Neuro',
      'LYNX': 'Lynx',
      'LINX': 'Linx',
      'LDCN': 'Landcoin',
      'KOBO': 'Kobocoin',
      'IXC': 'Ixcoin',
      'INSN': 'InsaneCoin',
      'THC': 'Hempcoin',
      'HNC': 'Helleniccoin',
      'GRC': 'Gridcoin',
      'GCR': 'Global Currency Reserve',
      'FRST': 'FirstCoin',
      'ERC': 'Europecoin',
      'EDRC': 'EDRcoin',
      'ECN': 'eCoin',
      'DGC': 'Digitalcoin',
      'DEFC': 'Defcoin',
      'CMP': 'CompCoin',
      'CCN': 'Cannacoin',
      'CDN': 'Canada eCoin',
      'BRIT': 'BritCoin',
      'XBC': 'BitcoinPlus',
      'BELA': 'BelaCoin',
      'USNBT': 'NuBits',
      'ONX': 'Onixcoin',
      'ZET': 'Zetacoin',
      'JBS': 'Jumbucks',
      'SLM': 'Slimcoin',
      'AXE': 'Axe',
      'PPC': 'Peercoin',
      'MZC': 'Mazacoin',
      'SDC': 'ShadowCash',
    },
  },
};